from abc import ABC

class BaseCallback(ABC):
    """Base class for all callbacks."""

    def on_train_start(self, trainer): ...
    def on_train_end(self, trainer): ...
    def on_epoch_start(self, trainer): ...
    def on_epoch_end(self, trainer): ...
    def on_step_end(self, trainer): ...
    def on_validation_end(self, trainer): ...
